# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bus_stop',
            field=models.IntegerField(default=2634),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.IntegerField(default=15213),
        ),
    ]
