# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170414_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ical_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
